# Generated by Django 4.2.1 on 2023-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
        ('post', '0005_remove_post_like_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='liked_posts', to='account.profile'),
        ),
    ]
