# Generated by Django 4.2.1 on 2023-05-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_rename_owner_comment_author_reply_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created']},
        ),
    ]
